### ISSUE TITLE
Classification - Labels matchar inte fågeln

### ISSUE THREAD

**Issue by BirWei-9** [TovahParnes/BirdAI_D7057E#153]

**Comment by anton-linden** [comment]
Labels matchar med samma bild i clusteret. Listan labels.json som är lokal i github matchar med cluster.

Misstanke om att bilder läses in fel eller ändras fel i classification?

**Comment by anton-linden** [comment]
Yes, confirmed, np ändrar utsendet på bilden. Man måste ladda in med keras image generator.
