### ISSUE TITLE
Classification - modell & lista innan start

### ISSUE THREAD

**Issue by BirWei-9** [TovahParnes/BirdAI_D7057E#175]
Kolla ifall modellen & label listan är med i projektet innan försök av uppstart.

Keras modellen & labels.json måste finnas i root på classification för att den ska kunna köras alls. Gör en check innan den försöker starta & crasha.

**Comment by anton-linden** [comment]
Done: https://github.com/TovahParnes/BirdAI_D7057E/pull/176
