### ISSUE TITLE
Ladda upp träningsskript och dokumentera träningsprocess

### ISSUE THREAD

**Issue by anton-linden** [TovahParnes/BirdAI_D7057E#211]
FInns ingen dokumentation hur vi tränar alls. Och vi har inte tillgång till skripten. Dessa bör finnas på google drive & ha någon dokumentation om hur vi ens tränar. Tex fil struktur för train/validate/test osv.

**Comment by Cordobro** [comment]
Skulle vara skönt att få lite feedback för vet inte hur strukturen av vår data skulle spela roll men skrivit lite gott och blandat om vilka dataset, hur vi pre-processat dem och resultat dem givit i ett dokument på driven under ljud och bild
