### ISSUE TITLE
Kontakta Cloud Admin

### ISSUE THREAD

**Issue by BirWei-9** [TovahParnes/BirdAI_D7057E#227]
Vi bör kontakta cloud admin för att fråga ifall vi skulle kunna få mer drive storage för ljudmodellens träning.

https://www.ltu.se/staff/s/sumrak-1.211823?l=en

**Comment by anton-linden** [comment]
![Image](https://github.com/TovahParnes/BirdAI_D7057E/assets/24540787/08988b80-9a08-4866-aaac-b864b535b325)
