### ISSUE TITLE
Planera med backend teamet för dataset

### ISSUE THREAD

**Issue by BirWei-9** [TovahParnes/BirdAI_D7057E#77]

**Comment by anton-linden** [comment]
Första 5 fåglarna enbart.

**Comment by anton-linden** [comment]
EURASIAN MAGPIE (Skata)

EURASIAN BULLFINCH (https://sv.wikipedia.org/wiki/Domherre#F%C3%B6rekomst_i_Sverige)

EUROPEAN GOLDFINCH (https://sv.wikipedia.org/wiki/Steglits#Status_i_Sverige)

BARN SWALLOW (https://sv.wikipedia.org/wiki/Ladusvala#Utbredning_i_Sverige)

BARN OWL https://sv.wikipedia.org/wiki/Tornuggla

HOUSE SPARROW https://en.wikipedia.org/wiki/House_sparrow

MALLARD DUCK (https://sv.wikipedia.org/wiki/Gr%C3%A4sand)
