### ISSUE TITLE
Look into multithreading for better preformance

### ISSUE THREAD

**Issue by BirWei-9** [TovahParnes/BirdAI_D7057E#86]

**Comment by anton-linden** [comment]
Behövs verkligen detta? Vi bör testa vilken prestanda vi har för tillfället för att se vad vi bör lägga tid på mest.

**Comment by Jovali99** [comment]
Resultat: Genomsnittliga svars tid för AI delen är 1.7 sekunder (testat med postman). Detta är rätt så snabbt ovanpå att concurrency inte verkar vara nått problem för tillfället. Detta betyder att vi mest troligen klarar oss utan multithreading för modellerna.
